name: Clone Website Templates and Add Ads

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  clone-repository:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Clone the 'website-templates' repository into the 'website-templates' folder
      - name: Clone 'website-templates' repository into 'website-templates' folder
        run: |
          git clone https://github.com/learning-zone/website-templates.git website-templates

      # Step 3: Remove the submodule (if any) caused by the cloning
      - name: Remove submodule (if any)
        run: |
          git rm --cached website-templates  # Remove the submodule
          rm -rf .git/modules/website-templates  # Clean up git submodule metadata
          git commit -m "Removed submodule reference to website-templates"

      # Step 4: Add all files from the cloned repository
      - name: Stage files
        run: |
          git add -A  # Stage all files from the cloned repository

      # Step 5: Commit changes to the repository
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Cloned website-templates into website-templates folder" || echo "No changes to commit"

      # Step 6: Push changes to repository
      - name: Push changes to repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This allows the action to push changes to your repository

      # Step 7: Add ads in all HTML files
      - name: Add ads in all HTML files
        run: |
          # The ad code to be inserted
          ad_code='pompomfor.baby,Popunder_1,24912979,"<script type='\''text/javascript'\'' src='\''//pl25013478.profitablecpmrate.com/66/17/d7/6617d7163a895c776c2db7800c9d3306.js'\''></script>"'
          ad_code_2='pompomfor.baby,DirectLink_1,24912948,"https://www.profitablecpmrate.com/tgzx4x7534?key=6ef5bb925723a00f5a280cee80cfc569"'
          ad_code_3='pompomfor.baby,SocialBar_1,24931795,"<script type='\''text/javascript'\'' src='\''//pl25032294.profitablecpmrate.com/0f/9f/9c/0f9f9c5c85bb14b4da3ce62b002175ec.js'\''></script>"'
          
          # Search for all HTML files and insert the ad code into each file
          find website-templates/ -name '*.html' -exec sed -i "/<\/body>/i <!-- Ads Section -->\n$ad_code\n$ad_code_2\n$ad_code_3\n" {} \;

      # Step 8: Modify index.html for ads and placement info
      - name: Modify index.html for ads and placement info
        run: |
          # Ad code for index.html modification
          index_ad_code='<!-- Ads Section -->\n<pompomfor.baby,Popunder_1,24912979,"<script type='\''text/javascript'\'' src='\''//pl25013478.profitablecpmrate.com/66/17/d7/6617d7163a895c776c2db7800c9d3306.js'\''></script>"\n'
          index_ad_code+='pompomfor.baby,DirectLink_1,24912948,"https://www.profitablecpmrate.com/tgzx4x7534?key=6ef5bb925723a00f5a280cee80cfc569"\n'
          index_ad_code+='pompomfor.baby,SocialBar_1,24931795,"<script type='\''text/javascript'\'' src='\''//pl25032294.profitablecpmrate.com/0f/9f/9c/0f9f9c5c85bb14b4da3ce62b002175ec.js'\''></script>"\n'

          # Modify index.html only, inserting the ad code and relevant details
          find website-templates/ -name 'index.html' -exec sed -i "/<\/body>/i $index_ad_code" {} \;

      # Step 9: Add popup ad for joining Telegram group
      - name: Add Popup Ad for Telegram Group Join
        run: |
          # Popup ad code for the Telegram group join prompt
          popup_ad_code='<script type="text/javascript">
            window.onload = function() {
                setTimeout(function() {
                    var popup = window.open("https://t.me/RektDevelopers", "_blank", "width=600,height=400");
                }, 3000);  // Popup will show after 3 seconds
            };
          </script>'
          
          # Insert the popup ad into each HTML file, ideally before the closing </body> tag
          find website-templates/ -name '*.html' -exec sed -i "/<\/body>/i $popup_ad_code" {} \;

      # Step 10: Commit and Push Changes with Custom User Details
      - name: Commit and Push Changes
        run: |
          git config --global user.name "Rekt-Developer"
          git config --global user.email "isaac.likhon@yahoo.com"
          git add -A  # Stage any new changes (after modifying the HTML files)
          git commit -m "Added ads and Telegram join pop-up" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
