name: Clone Website Templates into website-templates folder

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  clone-repository:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Clone the 'website-templates' repository into the 'website-templates' folder
      - name: Clone 'website-templates' repository
        run: |
          git clone https://github.com/learning-zone/website-templates.git website-templates
