name: Git Clone and Repository Statistics

on:
  schedule:
    # Run every 1 hour
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:

jobs:
  generate-repo-stats:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run the setup.sh script
      - name: Run Setup Script
        run: |
          chmod +x setup.sh
          ./setup.sh

      # Step 3: Git Search and Clone Trending Repos
      - name: Git Search and Clone Trending Repos
        run: |
          echo "Cloning trending repositories every hour..."
          mkdir -p repos
          cd repos
          # Clone trending repositories
          curl -s "https://api.github.com/search/repositories?q=stars:>1+sort:stars&per_page=5&page=1" |
          jq -r '.items[].html_url' | while read repo_url; do
            repo_name=$(basename $repo_url .git)
            if [ ! -d "$repo_name" ]; then
              git clone $repo_url
              echo "Cloned: $repo_name"
            fi
          done

      # Step 4: Generate HTML Report with Fork Buttons and Previews
      - name: Generate Repository Statistics HTML
        run: |
          echo "Generating HTML report for cloned repositories..."
          mkdir -p generated_html
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Git Templates Marketplace</title>
            <style>
              body { font-family: 'Arial', sans-serif; background: #f4f4f9; color: #333; }
              h1 { color: #222; }
              .repo { margin: 10px 0; padding: 10px; border: 1px solid #ddd; border-radius: 5px; }
              .repo a { text-decoration: none; color: #0066cc; }
              .repo button { margin-left: 10px; padding: 5px 10px; background-color: #4CAF50; color: white; border: none; cursor: pointer; }
              .repo img { width: 100%; height: 200px; object-fit: cover; }
            </style>
          </head>
          <body>
            <h1>Trending Repositories</h1>
            <p>Managed by: Rekt-Developer. Join our community at <a href='https://t.me/RektDevelopers'>t.me/RektDevelopers</a></p>
            $(for dir in $(ls repos); do
              echo "<div class='repo'>
                      <h3><a href='https://github.com/$dir' target='_blank'>$dir</a></h3>
                      <img src='https://placehold.it/500x300' alt='Repo Preview'>
                      <button onclick='window.location.href=\"https://github.com/$dir/fork\";'>Fork</button>
                    </div>"
            done)
          </body>
          </html>" > generated_html/index.html
          echo "HTML file generated successfully."
