name: Clone Templates, Setup, and Commit Changes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  clone-setup-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up Git Configuration
      - name: Set Up Git User
        run: |
          git config --global user.name "Rekt-Developer"
          git config --global user.email "isaac.likhon@yahoo.com"

      # Step 3: Run the setup.sh script (if needed for additional setup)
      - name: Run Setup Script
        run: |
          chmod +x setup.sh
          ./setup.sh

      # Step 4: Clone the repository with HTML5 templates
      - name: Clone website-templates repository
        run: |
          git clone https://github.com/learning-zone/website-templates.git website-templates

      # Step 5: Install dependencies (e.g., Python)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      # Step 6: Install Python dependencies
      - name: Install Python Dependencies
        run: |
          pip3 install pillow requests

      # Step 7: Run the Python script to generate index.html
      - name: Generate Index HTML
        run: |
          python3 generate_index.py

      # Step 8: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git add index.html
          git commit -m "Update index.html with new templates"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
